services:
  app-be:
    build:
      context: ./app-be
      dockerfile: Dockerfile
    container_name: fastify-app
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - devnet

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - devnet

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devnet

networks:
  devnet:

volumes:
  jenkins_home:
